### ISSUE TITLE
This library is deprecated

### ISSUE THREAD

**Issue by Deniz97** [speechmatics/speechmatics-python#42]
Hey, we tried to use this repo, and had to do some too-many fixes for it to be working with the current version of speechmatics, which is 3.8.

Couple of more important points:

- SM no longer returns "AudioAdded", instead it returns "DataAdded"
- Before sending each binary data, one should send a json data in following format:
           {
                "message": "AddData",
                "offset": 0,
                "seq_no": self.seq_no,
                "size": audio_chunk_size
            }
 - Weirdly, the "message_buffer_size" in models.py is used for the "count" of the buffer_sephamore, which is the lock used to make sure not to send too many chunks to bog down the SM instance.
 
 There were couple more fixes that i do not remember right now. I highly recomend for this repo to be updated, or make sure to troughly test the repo before using it (and apply the fixes).
 
 Our team may send out a pull-request later.

**Comment by funous** [comment]
Hi, the differences you describe seem to correspond to a very old v1 API, which is deprecated since RTVA 3.2.0. This client only works with the v2 API (which is the only supported API in RTVA). The main difference is the use of `/v2` in the endpoint URL - see https://docs.speechmatics.com/en/real-time-appliance/api-v2/api-example-usage/. The old API is still present, but is not supported and should not be used.

Can you see if using the v2 API endpoint works and if it still needs any code changes?

**Comment by Deniz97** [comment]
Yes you are right, we were using v1 api, i am terribly sorry and thank you for the quick response. No problem with v2 api.
